name: Lint & Test
on: push
jobs:
  lint:
    name: Lint
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npm run lint
  test:
    name: Test (jest)
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npm run test
